app/common/security/auth-service.js
app/src/app.js

also remove the x-access-token (assume it will be in the cookies)

redirect after you get an error

---

test/e2e/tasks/clip-data-polygon-task-spec.js
test/e2e/tasks/convert-to-kml-task-spec.js
test/e2e/tasks/zip-files-task-spec.js
test/pages/task-status-page.js

Scott, could you review my changes?
I added new page object for task-status and updated tests to use task-status-page object

new task-status-page object

---

app/index.html
app/src/cart/cart-items-query.js
app/src/cart/cart-service.js
app/src/cart/cart.html
app/src/taskrunner/cart-items.html
app/src/taskrunner/cart-items.js
app/src/taskrunner/invalid-items-controller.js
app/src/taskrunner/invalid-items-dialog.html
app/src/taskrunner/task-controller.js
app/src/taskrunner/task-modal-service.js
app/src/taskrunner/task-service.js
app/src/taskrunner/task.html
app/src/taskrunner/tasks-controller.js
app/src/taskrunner/tasks.html
app/styles/components/_queue.scss
app/styles/components/_tasks.scss
app/styles/components/modules/_task.scss
test/spec/taskrunner/cart-items-directive-spec.js
test/spec/taskrunner/task-controller-spec.js
test/spec/taskrunner/task-service-spec.js
test/spec/taskrunner/tasks-controller-spec.js

VG-716: Task validation changes and improvements

Task validation

---

app/src/config/config-service.js
app/src/layout/header-controller.js
app/src/layout/header.html
app/src/results/card.html
app/src/results/card.js
app/src/search/results-header.html
app/src/search/search-controller.js
app/src/search/search-view-list.html
app/src/search/search.html
app/styles/components/modules/_card.scss
app/styles/components/modules/_table_result.scss
test/mock/mocks.js
test/spec/search/search-controller-spec.js

most of the functionality to support the search results display config template changes.

Display config search results

---

app/src/config/config-service.js
app/src/details/detail-config.js
test/mock/mocks.js
test/spec/details/detail-config-spec.js

Also contains a rename from pageFramework to pageElements.

VG-3794, updating api calls back to display/config.

---

app/src/config/config-service.js
app/src/results/card.html
app/src/results/card.js
test/spec/config/config-service-spec.js
test/spec/results/card-directive-spec.js

also added unit tests to increase coverage.

VG-3741 Display config implementation for search results

---

app/src/cart/cart-nav-controller.js
app/src/taskrunner/task-controller.js
app/src/taskrunner/task-service.js
app/src/taskrunner/tasks-controller.js
test/spec/cart/cart-nav-controller-spec.js

VG-3859: support for defaultTask

VG-3859: support for defaultTask

---

app/src/results/card.js
app/src/results/table-results-controller.js
app/src/search/results-decorator.js

- Initial pass to format Dates

VG-3833 Format date time fields

---

app/src/config/config-loader.js
app/src/filters/catalog-service.js
app/src/search/results-decorator.js
test/spec/app/app-spec.js
test/spec/details/detail-config-spec.js
test/spec/filters/filters-controller-spec.js

VG-4508 - determine remote catalog comparing shard with federations

VG-4508 - determine remote catalog comparing shard with federations

---

app/src/details/detail-config.js

Updated to keep HREF styling if field value length is > 100 characters

VG-4308 - Updated to keep HREF styling if field value length is > 100 characters

---

app/common/util/url-util.js
app/index.html
app/src/app-config.js
app/src/cart/cart-nav.html
app/src/details/details-tab.html
app/src/details/details.js
app/src/details/relationships-tab.html
app/src/details/summary.html
app/src/jobs/view-jobs.html
app/src/jobs/view-jobs.js
app/src/layout/header-controller.js
app/src/layout/header.html
app/src/results/card.js
app/src/search/results-decorator.js
app/src/taskrunner/cart-items.html
app/src/taskrunner/params/view-items.html
app/src/taskrunner/status.js
app/src/taskrunner/task-controller.js
app/src/taskrunner/task.html
grunt/connect.js
grunt/regex-replace.js
package.json
test/.jshintrc
test/spec/app/app-spec.js
test/spec/details/preview-directive-spec.js
test/spec/details/tags-directive-spec.js
test/spec/jobs/jobs-controller-spec.js
test/spec/layout/header-controller-spec.js
test/spec/taskrunner/task-controller-spec.js

Remove hashes from states.  Use html5 mode. Set base dir.

seo - VG-3597

---

app/src/saved-search/save-search-dialog.html

Added Placeholder text to Save Search dialog

VG-4556 - When Saved Search Permission field is blank, include a feedback for users

---

app/src/search/results-decorator.js

Updated formatting of doc size to match the table view forother views during decoration

VG-4547 -  "File Size" on Cards/Map search results page not using units (bytes, MB, GB)

---

app/src/results/table-results.html

Updated to use link text instead of link display to display text for Preview link

VG-4619 - Table view has a Tools Open link and not Preview like on Card

---

app/src/saved-search/saved-search-service.js

Changes to prevent default of card from always overriding the default view from the display template

VG-4637 - Running a saved search from the selection list doesn't apply the display template default view

---

app/common/security/login.html
app/styles/components/_form.scss
app/styles/components/_variable.scss

Updated Styles and login html to make the login errors consistant with the cart error and to allow that error styling to be reusable

VG-4343 - User Login Screen Errors do not match errors throughout the rest of the application

---

app/src/details/detail-config.js

Updates to format file size in details page (will affect both details tab as well as summary fields)

VG-4751 - Update files size presentation on detail page

---

app/index.html
app/src/search/results-header.html
app/src/search/search.html
app/styles/components/_page.scss
bower.json

- Added EQCSS library for element based selectors

VG-3319 ssearch icon when filters open

---

test/e2e/home/home-spec.js
test/lib/util.js
test/pages/home-page.js

Added Home Page Tests
Added 2 methods to Util

VG-4874 - Homepage Tests

---

test/e2e/home/home-spec.js
test/lib/util.js
test/pages/home-page.js
test/pages/search-page.js

~Changed Search-Page click method to use util.patientClick to fix block-ui error that was occuring on Details-Page.

Details Page Test

---

app/src/search/results-decorator.js

For fields configured as HREF, use external HREFs in Search Results

VG-4738: External HREF on Search Results

---

app/src/component/table-results-directive.js

Resolved sizing issue by adding a timeout to wait for the map placement to change before calculating placement/dimensions of the results table

VG-4730 - Table View Not Displayed At Correct Ratio Initially

---

app/common/util/sugar.js
app/src/jobs/view-jobs.js
app/src/taskrunner/params/template-service.js
app/src/taskrunner/status.js
app/src/taskrunner/task-controller.js

@scottlepp, these are fixes to make a required parameter show an error and for the show details page having "missing template" error

Fixes for VG-5055 and 5504
